### ISSUE TITLE
Doesn't compile with 0.9.1 issue

### ISSUE THREAD

**Issue by akegalj** [afcondon/puxws#2]
is probably related to the issue described here http://ircbrowse.net/browse/purescript?id=367402&timestamp=1468886492#t1468886492 (just for you to have a reference to the discussion about wrongly inferred effect labels issue in types)

Do you know which version of `purescript`/ `pux` were you using when this was working? (it would be good to add those dependencies to `bower.json` and/or  `package.json`

**Comment by afcondon** [comment]
Thanks so much for letting me know.

I would really like it to be a compiler bug at this point!

## 

Andrew Condon

On 19 July 2016 at 03:44:19, Ante Kegalj (notifications@github.com) wrote:

is probably related to the issue described here
http://ircbrowse.net/browse/purescript?id=367402&timestamp=1468886492#t1468886492
(just for you to have a reference to the discussion about wrongly inferred
effect labels issue in types)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/afcondon/puxws/issues/2, or mute the thread

**Comment by akegalj** [comment]
Doesn't seem relevant any more. Closing
